### PR TITLE
Omar

### PR DESCRIPTION
**Pull request by oshorab**
Added add, delete, and update functions to multiple aspects of a User schema. Functions are created in UserController, and corresponding routes in user.js

### CODE REVIEW

**Comment by mattcuento** [comment]
Looks good to me except one thing. I see it didn't pass the linting test, could you fix those and then commit again?

**Comment by ncpalmie** [comment]
Looks good beyond the minor style issues as Matt noted

**Comment by Bart-Ilg** [comment]
Looks good as far as I can tell. Fix up the linting test Matt caught and I think it should be good

**Comment by EricInman** [comment]
Looks all good to me!

**Comment by mattcuento** [comment]
Looks good, linting checks out.

**Pull request merged**
